# Generated by Django 5.2.10 on 2026-02-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('desc', models.TextField()),
                ('category', models.CharField()),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
