# Generated by Django 5.2.10 on 2026-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('desc', models.TextField()),
                ('category', models.CharField()),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
